# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------
# Schemes
# scheme: Muse
# scheme: Mist
scheme: Pisces
# scheme: Gemini